import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Arimo } from "next/font/google";

import { ToastProvider } from "@/components/ui/toast";
import Navbar from "./(pages)/_components/Navbar";
import Footer from "./(pages)/_components/Footer";
import { ConvexClientProvider } from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  display: "swap",
  weight: ["400", "500", "600", "800"],
  style: "normal",
  variable: "--font-nunito",
});

const arimo = Arimo({
  display: "swap",
  weight: ["400", "500", "600"],
  style: "normal",
  variable: "--font-arimo",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} bg-[#FCF9F0] text-blue ${arimo.variable} antialiased font-arimo font-normal`}
      >
        <ConvexClientProvider>

        <ToastProvider>
          <Navbar />
          <div className="pointer-events-none absolute inset-0 sketch-dots" />
          {children}
          <Footer />
        </ToastProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
